-- Relay 初始 schema(Postgres)。与 0001_init.sql 一一对应。
-- 整数列统一用 BIGINT(与 Rust 侧 i64 读取一致);REAL -> DOUBLE PRECISION;
-- INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY。
-- 运行时由 storage::init_schema 以 IF NOT EXISTS 执行。

CREATE TABLE IF NOT EXISTS users (
  id                TEXT PRIMARY KEY,
  username          TEXT UNIQUE,
  password_hash     TEXT,
  email             TEXT,
  phone             TEXT UNIQUE,
  status            BIGINT NOT NULL DEFAULT 0,        -- 0=active 1=disabled
  token_balance     BIGINT NOT NULL,
  token_used_total  BIGINT NOT NULL DEFAULT 0,
  concurrency_limit BIGINT,                            -- NULL=用全局默认
  bill_multiplier   DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  group_id          BIGINT,
  rpm_limit         BIGINT,                            -- NULL=用全局默认
  tpm_limit         BIGINT,                            -- NULL=用全局默认
  budget_daily_tokens  BIGINT,                         -- 日预算(charged tokens,NULL=不限)
  budget_monthly_tokens BIGINT,                        -- 月预算(charged tokens,NULL=不限)
  source            TEXT,
  created_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
  id             TEXT PRIMARY KEY,
  user_id        TEXT NOT NULL,
  interface_kind TEXT NOT NULL,
  key_hash       TEXT NOT NULL UNIQUE,
  key_prefix     TEXT NOT NULL,
  key_plain      TEXT,                             -- 完整 Key 明文:门户端随时查看/复制(认证仍走 key_hash)
  revoked        BIGINT NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_logs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        TEXT NOT NULL,
  model          TEXT,
  provider       TEXT,
  upstream_model TEXT,
  input_tokens   BIGINT,
  output_tokens  BIGINT,
  charged_tokens BIGINT,
  key_id         TEXT,
  cost_usd       DOUBLE PRECISION,
  status         BIGINT,
  ts             BIGINT NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL,
  request_id     TEXT
);
CREATE INDEX IF NOT EXISTS idx_usage_user ON usage_logs(user_id, ts);

-- 请求链路追踪:记录每次请求(成功+失败)的路由候选顺序、权重、实际选中、failover 链。
CREATE TABLE IF NOT EXISTS request_logs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id         TEXT NOT NULL,
  user_id            TEXT NOT NULL,
  path               TEXT,
  requested_model    TEXT,
  stream             BIGINT NOT NULL DEFAULT 0,
  candidates         TEXT,
  attempts           TEXT,
  final_kind         TEXT,
  final_upstream_model TEXT,
  final_status       BIGINT,
  latency_ms         BIGINT NOT NULL DEFAULT 0,
  input_tokens       BIGINT NOT NULL DEFAULT 0,
  output_tokens      BIGINT NOT NULL DEFAULT 0,
  charged_tokens     BIGINT NOT NULL DEFAULT 0,
  req_body           TEXT,
  resp_body          TEXT,
  created_at         TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reqlog_user ON request_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_reqlog_reqid ON request_logs(request_id);
CREATE INDEX IF NOT EXISTS idx_reqlog_status_created ON request_logs(final_status, created_at);
CREATE INDEX IF NOT EXISTS idx_reqlog_created ON request_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_usage_user_tokens ON usage_logs(user_id, charged_tokens);

CREATE TABLE IF NOT EXISTS providers (
  name         TEXT PRIMARY KEY,
  kind         TEXT NOT NULL,
  base_url     TEXT NOT NULL,
  api_key      TEXT,
  display_name TEXT,                      -- 自定义显示名(空=按域名展示)
  created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS models (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider       TEXT NOT NULL,
  upstream_model TEXT NOT NULL,
  label          TEXT,
  input_price    DOUBLE PRECISION,          -- 输入单价 $/1M tokens(NULL=未定价)
  output_price   DOUBLE PRECISION,          -- 输出单价 $/1M tokens(NULL=未定价)
  created_at     TEXT NOT NULL,
  UNIQUE (provider, upstream_model)
);

CREATE TABLE IF NOT EXISTS model_groups (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  is_active  BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS group_routes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    BIGINT NOT NULL,
  public_name TEXT NOT NULL,
  model_id    BIGINT NOT NULL,
  weight      BIGINT NOT NULL DEFAULT 100,
  multiplier  DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  cache_enabled BIGINT NOT NULL DEFAULT 0,    -- 路由级语义缓存 opt-in(1=参与缓存判定)
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reward_tasks (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  evidence_type TEXT NOT NULL DEFAULT 'text',  -- screenshot | link | text | none
  variable      BIGINT NOT NULL DEFAULT 0,     -- 0=固定额度 1=区间(管理员审核时评定)
  reward_tokens BIGINT NOT NULL DEFAULT 0,
  reward_min    BIGINT NOT NULL DEFAULT 0,
  reward_max    BIGINT NOT NULL DEFAULT 0,
  link_url      TEXT,
  enabled       BIGINT NOT NULL DEFAULT 1,
  sort          BIGINT NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reward_claims (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL,
  task_id       BIGINT,
  kind          TEXT,                          -- 兼容旧字段:star | issue | suggestion
  evidence      TEXT,
  reward_tokens BIGINT NOT NULL,
  status        BIGINT NOT NULL DEFAULT 0,    -- 0=pending 1=approved 2=rejected
  review_note   TEXT,
  reviewed_at   TEXT,
  created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reward_user ON reward_claims(user_id);

-- 系统配置(KV)。点分命名空间,如 email.smtp_host。value 统一 TEXT(标量直存,复杂值 JSON)。
CREATE TABLE IF NOT EXISTS settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- 高峰/低谷时段策略:按「星期 + 时间段」驱动 计费倍率 与 路由权重覆盖。
CREATE TABLE IF NOT EXISTS time_rules (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    BIGINT NOT NULL,
  name        TEXT NOT NULL,
  weekdays    TEXT NOT NULL DEFAULT '0-6',      -- 生效星期:0-6 或 "1-5" / "0,6" / "0-6"
  start_time  TEXT NOT NULL,                    -- 开始 HH:MM
  end_time    TEXT NOT NULL,                    -- 结束 HH:MM
  multiplier  DOUBLE PRECISION NOT NULL DEFAULT 1.0, -- 该时段计费倍率系数
  weight_map  TEXT,                             -- 该时段路由权重覆盖 JSON
  active      BIGINT NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL
);

-- 语义缓存 L2:请求文本的 embedding 向量(按 model+provider 隔离,暴力余弦扫描)。
CREATE TABLE IF NOT EXISTS cache_vectors (
  cache_key  TEXT PRIMARY KEY,              -- 对应内存缓存的 key(L2 命中后回查 L1 取响应体)
  model      TEXT NOT NULL,                 -- 公开模型名(隔离维度)
  provider   TEXT NOT NULL,                 -- 供应商名(隔离维度)
  embedding  TEXT NOT NULL,                 -- f32 向量 base64(little-endian 字节)
  created_at BIGINT NOT NULL                -- unix 秒(用于按龄清理)
);
CREATE INDEX IF NOT EXISTS idx_cache_vectors_scope ON cache_vectors(model, provider);

-- 管理操作审计:admin 面所有变更请求(POST/PUT/PATCH/DELETE)统一落库。
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor      TEXT NOT NULL,                -- 操作者(admin 用户名);无 token 请求(登录)为 anonymous
  method     TEXT NOT NULL,                -- POST | PUT | PATCH | DELETE
  path       TEXT NOT NULL,                -- 请求路径(如 /admin/api/users)
  status     BIGINT NOT NULL,              -- 响应状态码
  ip         TEXT NOT NULL DEFAULT '',     -- 客户端 IP
  latency_ms BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON admin_audit_logs(created_at);
