-- RunAPI 初始 schema(Postgres)。与 0001_init.sql 一一对应。
-- 整数列统一用 BIGINT(与 Rust 侧 i64 读取一致);REAL -> DOUBLE PRECISION;
-- INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY。
-- 运行时由 storage::init_schema 以 IF NOT EXISTS 执行。

CREATE TABLE IF NOT EXISTS users (
  id                TEXT PRIMARY KEY,
  username          TEXT UNIQUE,
  password_hash     TEXT,
  email             TEXT,
  phone             TEXT UNIQUE,
  status            BIGINT NOT NULL DEFAULT 0,        -- 0=active 1=disabled
  token_balance     BIGINT NOT NULL,
  token_used_total  BIGINT NOT NULL DEFAULT 0,
  concurrency_limit BIGINT,                            -- NULL=用全局默认
  bill_multiplier   DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  group_id          BIGINT,
  source            TEXT,
  created_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
  id             TEXT PRIMARY KEY,
  user_id        TEXT NOT NULL,
  interface_kind TEXT NOT NULL,
  key_hash       TEXT NOT NULL UNIQUE,
  key_prefix     TEXT NOT NULL,
  revoked        BIGINT NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_logs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        TEXT NOT NULL,
  model          TEXT,
  provider       TEXT,
  upstream_model TEXT,
  input_tokens   BIGINT,
  output_tokens  BIGINT,
  charged_tokens BIGINT,
  status         BIGINT,
  ts             BIGINT NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_usage_user ON usage_logs(user_id, ts);

CREATE TABLE IF NOT EXISTS providers (
  name        TEXT PRIMARY KEY,
  kind        TEXT NOT NULL,
  base_url    TEXT NOT NULL,
  api_key     TEXT,
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS models (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider       TEXT NOT NULL,
  upstream_model TEXT NOT NULL,
  label          TEXT,
  created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS model_groups (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  is_active  BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS group_routes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    BIGINT NOT NULL,
  public_name TEXT NOT NULL,
  model_id    BIGINT NOT NULL,
  weight      BIGINT NOT NULL DEFAULT 100,
  multiplier  DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reward_tasks (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  description   TEXT,
  evidence_type TEXT NOT NULL DEFAULT 'text',  -- screenshot | link | text | none
  variable      BIGINT NOT NULL DEFAULT 0,     -- 0=固定额度 1=区间(管理员审核时评定)
  reward_tokens BIGINT NOT NULL DEFAULT 0,
  reward_min    BIGINT NOT NULL DEFAULT 0,
  reward_max    BIGINT NOT NULL DEFAULT 0,
  link_url      TEXT,
  enabled       BIGINT NOT NULL DEFAULT 1,
  sort          BIGINT NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reward_claims (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL,
  task_id       BIGINT,
  kind          TEXT,                          -- 兼容旧字段:star | issue | suggestion
  evidence      TEXT,
  reward_tokens BIGINT NOT NULL,
  status        BIGINT NOT NULL DEFAULT 0,    -- 0=pending 1=approved 2=rejected
  review_note   TEXT,
  reviewed_at   TEXT,
  created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reward_user ON reward_claims(user_id);
